/**
 * MIT License
 * <p>
 * Copyright (c) 2018 grndctl-akka
 * <p>
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * <p>
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * <p>
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.06 at 02:17:36 PM EST 
//

package com.grndctl.model.pirep;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}receipt_time" minOccurs="0"/>
 *         &lt;element ref="{}observation_time" minOccurs="0"/>
 *         &lt;element ref="{}quality_control_flags" minOccurs="0"/>
 *         &lt;element ref="{}aircraft_ref" minOccurs="0"/>
 *         &lt;element ref="{}latitude" minOccurs="0"/>
 *         &lt;element ref="{}longitude" minOccurs="0"/>
 *         &lt;element ref="{}altitude_ft_msl" minOccurs="0"/>
 *         &lt;element ref="{}sky_condition" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}turbulence_condition" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}icing_condition" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}visibility_statute_mi" minOccurs="0"/>
 *         &lt;element ref="{}wx_string" minOccurs="0"/>
 *         &lt;element ref="{}temp_c" minOccurs="0"/>
 *         &lt;element ref="{}wind_dir_degrees" minOccurs="0"/>
 *         &lt;element ref="{}wind_speed_kt" minOccurs="0"/>
 *         &lt;element ref="{}vert_gust_kt" minOccurs="0"/>
 *         &lt;element ref="{}pirep_type" minOccurs="0"/>
 *         &lt;element ref="{}raw_text" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"receiptTime", "observationTime",
        "qualityControlFlags", "aircraftRef", "latitude", "longitude",
        "altitudeFtMsl", "skyCondition", "turbulenceCondition",
        "icingCondition", "visibilityStatuteMi", "wxString", "tempC",
        "windDirDegrees", "windSpeedKt", "vertGustKt", "pirepType", "rawText"})
@XmlRootElement(name = "PIREP")
public class PIREP {

    @XmlElement(name = "receipt_time")
    protected String receiptTime;
    @XmlElement(name = "observation_time")
    protected String observationTime;
    @XmlElement(name = "quality_control_flags")
    protected QualityControlFlags qualityControlFlags;
    @XmlElement(name = "aircraft_ref")
    protected String aircraftRef;
    protected Float latitude;
    protected Float longitude;
    @XmlElement(name = "altitude_ft_msl")
    protected Integer altitudeFtMsl;
    @XmlElement(name = "sky_condition")
    protected List<SkyCondition> skyCondition;
    @XmlElement(name = "turbulence_condition")
    protected List<TurbulenceCondition> turbulenceCondition;
    @XmlElement(name = "icing_condition")
    protected List<IcingCondition> icingCondition;
    @XmlElement(name = "visibility_statute_mi")
    protected Integer visibilityStatuteMi;
    @XmlElement(name = "wx_string")
    protected String wxString;
    @XmlElement(name = "temp_c")
    protected Float tempC;
    @XmlElement(name = "wind_dir_degrees")
    protected Integer windDirDegrees;
    @XmlElement(name = "wind_speed_kt")
    protected Integer windSpeedKt;
    @XmlElement(name = "vert_gust_kt")
    protected Integer vertGustKt;
    @XmlElement(name = "pirep_type")
    protected String pirepType;
    @XmlElement(name = "raw_text")
    protected String rawText;

    /**
     * Gets the fromString of the receiptTime property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getReceiptTime() {
        return receiptTime;
    }

    /**
     * Sets the fromString of the receiptTime property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setReceiptTime(String value) {
        this.receiptTime = value;
    }

    /**
     * Gets the fromString of the observationTime property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getObservationTime() {
        return observationTime;
    }

    /**
     * Sets the fromString of the observationTime property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setObservationTime(String value) {
        this.observationTime = value;
    }

    /**
     * Gets the fromString of the qualityControlFlags property.
     *
     * @return possible object is {@link QualityControlFlags }
     *
     */
    public QualityControlFlags getQualityControlFlags() {
        return qualityControlFlags;
    }

    /**
     * Sets the fromString of the qualityControlFlags property.
     *
     * @param value
     *            allowed object is {@link QualityControlFlags }
     *
     */
    public void setQualityControlFlags(QualityControlFlags value) {
        this.qualityControlFlags = value;
    }

    /**
     * Gets the fromString of the aircraftRef property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getAircraftRef() {
        return aircraftRef;
    }

    /**
     * Sets the fromString of the aircraftRef property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setAircraftRef(String value) {
        this.aircraftRef = value;
    }

    /**
     * Gets the fromString of the latitude property.
     *
     * @return possible object is {@link Float }
     *
     */
    public Float getLatitude() {
        return latitude;
    }

    /**
     * Sets the fromString of the latitude property.
     *
     * @param value
     *            allowed object is {@link Float }
     *
     */
    public void setLatitude(Float value) {
        this.latitude = value;
    }

    /**
     * Gets the fromString of the longitude property.
     *
     * @return possible object is {@link Float }
     *
     */
    public Float getLongitude() {
        return longitude;
    }

    /**
     * Sets the fromString of the longitude property.
     *
     * @param value
     *            allowed object is {@link Float }
     *
     */
    public void setLongitude(Float value) {
        this.longitude = value;
    }

    /**
     * Gets the fromString of the altitudeFtMsl property.
     *
     * @return possible object is {@link Integer }
     *
     */
    public Integer getAltitudeFtMsl() {
        return altitudeFtMsl;
    }

    /**
     * Sets the fromString of the altitudeFtMsl property.
     *
     * @param value
     *            allowed object is {@link Integer }
     *
     */
    public void setAltitudeFtMsl(Integer value) {
        this.altitudeFtMsl = value;
    }

    /**
     * Gets the fromString of the skyCondition property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the skyCondition property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getSkyCondition().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SkyCondition }
     *
     *
     */
    public List<SkyCondition> getSkyCondition() {
        if (skyCondition == null) {
            skyCondition = new ArrayList<SkyCondition>();
        }
        return this.skyCondition;
    }

    /**
     * Gets the fromString of the turbulenceCondition property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the turbulenceCondition property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getTurbulenceCondition().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TurbulenceCondition }
     *
     *
     */
    public List<TurbulenceCondition> getTurbulenceCondition() {
        if (turbulenceCondition == null) {
            turbulenceCondition = new ArrayList<TurbulenceCondition>();
        }
        return this.turbulenceCondition;
    }

    /**
     * Gets the fromString of the icingCondition property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the icingCondition property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getIcingCondition().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IcingCondition }
     *
     *
     */
    public List<IcingCondition> getIcingCondition() {
        if (icingCondition == null) {
            icingCondition = new ArrayList<IcingCondition>();
        }
        return this.icingCondition;
    }

    /**
     * Gets the fromString of the visibilityStatuteMi property.
     *
     * @return possible object is {@link Integer }
     *
     */
    public Integer getVisibilityStatuteMi() {
        return visibilityStatuteMi;
    }

    /**
     * Sets the fromString of the visibilityStatuteMi property.
     *
     * @param value
     *            allowed object is {@link Integer }
     *
     */
    public void setVisibilityStatuteMi(Integer value) {
        this.visibilityStatuteMi = value;
    }

    /**
     * Gets the fromString of the wxString property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getWxString() {
        return wxString;
    }

    /**
     * Sets the fromString of the wxString property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setWxString(String value) {
        this.wxString = value;
    }

    /**
     * Gets the fromString of the tempC property.
     *
     * @return possible object is {@link Float }
     *
     */
    public Float getTempC() {
        return tempC;
    }

    /**
     * Sets the fromString of the tempC property.
     *
     * @param value
     *            allowed object is {@link Float }
     *
     */
    public void setTempC(Float value) {
        this.tempC = value;
    }

    /**
     * Gets the fromString of the windDirDegrees property.
     *
     * @return possible object is {@link Integer }
     *
     */
    public Integer getWindDirDegrees() {
        return windDirDegrees;
    }

    /**
     * Sets the fromString of the windDirDegrees property.
     *
     * @param value
     *            allowed object is {@link Integer }
     *
     */
    public void setWindDirDegrees(Integer value) {
        this.windDirDegrees = value;
    }

    /**
     * Gets the fromString of the windSpeedKt property.
     *
     * @return possible object is {@link Integer }
     *
     */
    public Integer getWindSpeedKt() {
        return windSpeedKt;
    }

    /**
     * Sets the fromString of the windSpeedKt property.
     *
     * @param value
     *            allowed object is {@link Integer }
     *
     */
    public void setWindSpeedKt(Integer value) {
        this.windSpeedKt = value;
    }

    /**
     * Gets the fromString of the vertGustKt property.
     *
     * @return possible object is {@link Integer }
     *
     */
    public Integer getVertGustKt() {
        return vertGustKt;
    }

    /**
     * Sets the fromString of the vertGustKt property.
     *
     * @param value
     *            allowed object is {@link Integer }
     *
     */
    public void setVertGustKt(Integer value) {
        this.vertGustKt = value;
    }

    /**
     * Gets the fromString of the pirepType property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getPirepType() {
        return pirepType;
    }

    /**
     * Sets the fromString of the pirepType property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setPirepType(String value) {
        this.pirepType = value;
    }

    /**
     * Gets the fromString of the rawText property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getRawText() {
        return rawText;
    }

    /**
     * Sets the fromString of the rawText property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setRawText(String value) {
        this.rawText = value;
    }

}
