/**
 * MIT License
 * <p>
 * Copyright (c) 2018 grndctl-akka
 * <p>
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * <p>
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * <p>
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.06 at 02:16:35 PM EST 
//

package com.grndctl.model.airsigmet;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}raw_text" minOccurs="0"/>
 *         &lt;element ref="{}valid_time_from" minOccurs="0"/>
 *         &lt;element ref="{}valid_time_to" minOccurs="0"/>
 *         &lt;element ref="{}altitude" minOccurs="0"/>
 *         &lt;element ref="{}movement_dir_degrees" minOccurs="0"/>
 *         &lt;element ref="{}movement_speed_kt" minOccurs="0"/>
 *         &lt;element ref="{}hazard" minOccurs="0"/>
 *         &lt;element ref="{}airsigmet_type" minOccurs="0"/>
 *         &lt;element ref="{}area" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"rawText", "validTimeFrom", "validTimeTo",
        "altitude", "movementDirDegrees", "movementSpeedKt", "hazard",
        "airsigmetType", "area"})
@XmlRootElement(name = "AIRSIGMET")
public class AIRSIGMET {

    @XmlElement(name = "raw_text")
    protected String rawText;
    @XmlElement(name = "valid_time_from")
    protected String validTimeFrom;
    @XmlElement(name = "valid_time_to")
    protected String validTimeTo;
    protected Altitude altitude;
    @XmlElement(name = "movement_dir_degrees")
    protected BigInteger movementDirDegrees;
    @XmlElement(name = "movement_speed_kt")
    protected BigInteger movementSpeedKt;
    protected Hazard hazard;
    @XmlElement(name = "airsigmet_type")
    protected String airsigmetType;
    protected List<Area> area;

    /**
     * Gets the fromString of the rawText property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getRawText() {
        return rawText;
    }

    /**
     * Sets the fromString of the rawText property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setRawText(String value) {
        this.rawText = value;
    }

    /**
     * Gets the fromString of the validTimeFrom property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getValidTimeFrom() {
        return validTimeFrom;
    }

    /**
     * Sets the fromString of the validTimeFrom property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setValidTimeFrom(String value) {
        this.validTimeFrom = value;
    }

    /**
     * Gets the fromString of the validTimeTo property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getValidTimeTo() {
        return validTimeTo;
    }

    /**
     * Sets the fromString of the validTimeTo property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setValidTimeTo(String value) {
        this.validTimeTo = value;
    }

    /**
     * Gets the fromString of the altitude property.
     *
     * @return possible object is {@link Altitude }
     *
     */
    public Altitude getAltitude() {
        return altitude;
    }

    /**
     * Sets the fromString of the altitude property.
     *
     * @param value
     *            allowed object is {@link Altitude }
     *
     */
    public void setAltitude(Altitude value) {
        this.altitude = value;
    }

    /**
     * Gets the fromString of the movementDirDegrees property.
     *
     * @return possible object is {@link BigInteger }
     *
     */
    public BigInteger getMovementDirDegrees() {
        return movementDirDegrees;
    }

    /**
     * Sets the fromString of the movementDirDegrees property.
     *
     * @param value
     *            allowed object is {@link BigInteger }
     *
     */
    public void setMovementDirDegrees(BigInteger value) {
        this.movementDirDegrees = value;
    }

    /**
     * Gets the fromString of the movementSpeedKt property.
     *
     * @return possible object is {@link BigInteger }
     *
     */
    public BigInteger getMovementSpeedKt() {
        return movementSpeedKt;
    }

    /**
     * Sets the fromString of the movementSpeedKt property.
     *
     * @param value
     *            allowed object is {@link BigInteger }
     *
     */
    public void setMovementSpeedKt(BigInteger value) {
        this.movementSpeedKt = value;
    }

    /**
     * Gets the fromString of the hazard property.
     *
     * @return possible object is {@link Hazard }
     *
     */
    public Hazard getHazard() {
        return hazard;
    }

    /**
     * Sets the fromString of the hazard property.
     *
     * @param value
     *            allowed object is {@link Hazard }
     *
     */
    public void setHazard(Hazard value) {
        this.hazard = value;
    }

    /**
     * Gets the fromString of the airsigmetType property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getAirsigmetType() {
        return airsigmetType;
    }

    /**
     * Sets the fromString of the airsigmetType property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setAirsigmetType(String value) {
        this.airsigmetType = value;
    }

    /**
     * Gets the fromString of the area property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the area property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getArea().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Area }
     *
     *
     */
    public List<Area> getArea() {
        if (area == null) {
            area = new ArrayList<Area>();
        }
        return this.area;
    }

}
