/**
 * MIT License
 * <p>
 * Copyright (c) 2018 grndctl-akka
 * <p>
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * <p>
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * <p>
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.06 at 02:18:33 PM EST 
//

package com.grndctl.model.station;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the com.groundcontrol.station package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ElevationM_QNAME = new QName("", "elevation_m");
    private final static QName _Country_QNAME = new QName("", "country");
    private final static QName _WindProfiler_QNAME = new QName("",
            "wind_profiler");
    private final static QName _WmoId_QNAME = new QName("", "wmo_id");
    private final static QName _RequestIndex_QNAME = new QName("",
            "request_index");
    private final static QName _StationId_QNAME = new QName("", "station_id");
    private final static QName _Latitude_QNAME = new QName("", "latitude");
    private final static QName _SYNOPS_QNAME = new QName("", "SYNOPS");
    private final static QName _TimeTakenMs_QNAME = new QName("",
            "time_taken_ms");
    private final static QName _Error_QNAME = new QName("", "error");
    private final static QName _METAR_QNAME = new QName("", "METAR");
    private final static QName _Site_QNAME = new QName("", "site");
    private final static QName _WFOOffice_QNAME = new QName("", "WFO_office");
    private final static QName _TAF_QNAME = new QName("", "TAF");
    private final static QName _Warning_QNAME = new QName("", "warning");
    private final static QName _State_QNAME = new QName("", "state");
    private final static QName _NEXRAD_QNAME = new QName("", "NEXRAD");
    private final static QName _Rawinsonde_QNAME = new QName("", "rawinsonde");
    private final static QName _Longitude_QNAME = new QName("", "longitude");

    /**
     * Create a new ObjectFactory that can be used to create new instances of
     * schema derived classes for package: com.groundcontrol.station
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Request }
     *
     */
    public Request createRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link Data }
     *
     */
    public Data createData() {
        return new Data();
    }

    /**
     * Create an instance of {@link Station }
     *
     */
    public Station createStation() {
        return new Station();
    }

    /**
     * Create an instance of {@link SiteType }
     *
     */
    public SiteType createSiteType() {
        return new SiteType();
    }

    /**
     * Create an instance of {@link Warnings }
     *
     */
    public Warnings createWarnings() {
        return new Warnings();
    }

    /**
     * Create an instance of {@link DataSource }
     *
     */
    public DataSource createDataSource() {
        return new DataSource();
    }

    /**
     * Create an instance of {@link Response }
     *
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link Errors }
     *
     */
    public Errors createErrors() {
        return new Errors();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "elevation_m")
    public JAXBElement<Float> createElevationM(Float value) {
        return new JAXBElement<Float>(_ElevationM_QNAME, Float.class, null,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "country")
    public JAXBElement<String> createCountry(String value) {
        return new JAXBElement<String>(_Country_QNAME, String.class, null,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "wind_profiler")
    public JAXBElement<Object> createWindProfiler(Object value) {
        return new JAXBElement<Object>(_WindProfiler_QNAME, Object.class, null,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "wmo_id")
    public JAXBElement<String> createWmoId(String value) {
        return new JAXBElement<String>(_WmoId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "request_index")
    public JAXBElement<Integer> createRequestIndex(Integer value) {
        return new JAXBElement<Integer>(_RequestIndex_QNAME, Integer.class,
                null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "station_id")
    public JAXBElement<String> createStationId(String value) {
        return new JAXBElement<String>(_StationId_QNAME, String.class, null,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "latitude")
    public JAXBElement<Float> createLatitude(Float value) {
        return new JAXBElement<Float>(_Latitude_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "SYNOPS")
    public JAXBElement<Object> createSYNOPS(Object value) {
        return new JAXBElement<Object>(_SYNOPS_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "time_taken_ms")
    public JAXBElement<Integer> createTimeTakenMs(Integer value) {
        return new JAXBElement<Integer>(_TimeTakenMs_QNAME, Integer.class,
                null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "error")
    public JAXBElement<String> createError(String value) {
        return new JAXBElement<String>(_Error_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "METAR")
    public JAXBElement<Object> createMETAR(Object value) {
        return new JAXBElement<Object>(_METAR_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "site")
    public JAXBElement<String> createSite(String value) {
        return new JAXBElement<String>(_Site_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "WFO_office")
    public JAXBElement<Object> createWFOOffice(Object value) {
        return new JAXBElement<Object>(_WFOOffice_QNAME, Object.class, null,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "TAF")
    public JAXBElement<Object> createTAF(Object value) {
        return new JAXBElement<Object>(_TAF_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "warning")
    public JAXBElement<String> createWarning(String value) {
        return new JAXBElement<String>(_Warning_QNAME, String.class, null,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "state")
    public JAXBElement<String> createState(String value) {
        return new JAXBElement<String>(_State_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "NEXRAD")
    public JAXBElement<Object> createNEXRAD(Object value) {
        return new JAXBElement<Object>(_NEXRAD_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "rawinsonde")
    public JAXBElement<Object> createRawinsonde(Object value) {
        return new JAXBElement<Object>(_Rawinsonde_QNAME, Object.class, null,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "longitude")
    public JAXBElement<Float> createLongitude(Float value) {
        return new JAXBElement<Float>(_Longitude_QNAME, Float.class, null,
                value);
    }

}
