/**
 * MIT License
 * <p>
 * Copyright (c) 2018 grndctl-akka
 * <p>
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * <p>
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * <p>
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.06 at 02:17:20 PM EST 
//

package com.grndctl.model.metar;

import javax.xml.bind.annotation.*;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}corrected" minOccurs="0"/>
 *         &lt;element ref="{}auto" minOccurs="0"/>
 *         &lt;element ref="{}auto_station" minOccurs="0"/>
 *         &lt;element ref="{}maintenance_indicator_on" minOccurs="0"/>
 *         &lt;element ref="{}no_signal" minOccurs="0"/>
 *         &lt;element ref="{}lightning_sensor_off" minOccurs="0"/>
 *         &lt;element ref="{}freezing_rain_sensor_off" minOccurs="0"/>
 *         &lt;element ref="{}present_weather_sensor_off" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"corrected", "auto", "autoStation",
        "maintenanceIndicatorOn", "noSignal", "lightningSensorOff",
        "freezingRainSensorOff", "presentWeatherSensorOff"})
@XmlRootElement(name = "quality_control_flags")
public class QualityControlFlags {

    protected String corrected;
    protected String auto;
    @XmlElement(name = "auto_station")
    protected String autoStation;
    @XmlElement(name = "maintenance_indicator_on")
    protected String maintenanceIndicatorOn;
    @XmlElement(name = "no_signal")
    protected String noSignal;
    @XmlElement(name = "lightning_sensor_off")
    protected String lightningSensorOff;
    @XmlElement(name = "freezing_rain_sensor_off")
    protected String freezingRainSensorOff;
    @XmlElement(name = "present_weather_sensor_off")
    protected String presentWeatherSensorOff;

    /**
     * Gets the fromString of the corrected property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getCorrected() {
        return corrected;
    }

    /**
     * Sets the fromString of the corrected property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setCorrected(String value) {
        this.corrected = value;
    }

    /**
     * Gets the fromString of the auto property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getAuto() {
        return auto;
    }

    /**
     * Sets the fromString of the auto property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setAuto(String value) {
        this.auto = value;
    }

    /**
     * Gets the fromString of the autoStation property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getAutoStation() {
        return autoStation;
    }

    /**
     * Sets the fromString of the autoStation property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setAutoStation(String value) {
        this.autoStation = value;
    }

    /**
     * Gets the fromString of the maintenanceIndicatorOn property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getMaintenanceIndicatorOn() {
        return maintenanceIndicatorOn;
    }

    /**
     * Sets the fromString of the maintenanceIndicatorOn property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setMaintenanceIndicatorOn(String value) {
        this.maintenanceIndicatorOn = value;
    }

    /**
     * Gets the fromString of the noSignal property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getNoSignal() {
        return noSignal;
    }

    /**
     * Sets the fromString of the noSignal property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setNoSignal(String value) {
        this.noSignal = value;
    }

    /**
     * Gets the fromString of the lightningSensorOff property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getLightningSensorOff() {
        return lightningSensorOff;
    }

    /**
     * Sets the fromString of the lightningSensorOff property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setLightningSensorOff(String value) {
        this.lightningSensorOff = value;
    }

    /**
     * Gets the fromString of the freezingRainSensorOff property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getFreezingRainSensorOff() {
        return freezingRainSensorOff;
    }

    /**
     * Sets the fromString of the freezingRainSensorOff property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setFreezingRainSensorOff(String value) {
        this.freezingRainSensorOff = value;
    }

    /**
     * Gets the fromString of the presentWeatherSensorOff property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getPresentWeatherSensorOff() {
        return presentWeatherSensorOff;
    }

    /**
     * Sets the fromString of the presentWeatherSensorOff property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setPresentWeatherSensorOff(String value) {
        this.presentWeatherSensorOff = value;
    }

}
