/**
 * MIT License
 * <p>
 * Copyright (c) 2017 grndctl
 * <p>
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * <p>
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * <p>
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.06 at 02:18:46 PM EST 
//

package com.grndctl.model.taf;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the com.groundcontrol.taf package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _WindShearHgtFtAgl_QNAME = new QName("",
            "wind_shear_hgt_ft_agl");
    private final static QName _VisibilityStatuteMi_QNAME = new QName("",
            "visibility_statute_mi");
    private final static QName _Latitude_QNAME = new QName("", "latitude");
    private final static QName _TimeTakenMs_QNAME = new QName("",
            "time_taken_ms");
    private final static QName _BulletinTime_QNAME = new QName("",
            "bulletin_time");
    private final static QName _WindShearSpeedKt_QNAME = new QName("",
            "wind_shear_speed_kt");
    private final static QName _Error_QNAME = new QName("", "error");
    private final static QName _WxString_QNAME = new QName("", "wx_string");
    private final static QName _NotDecoded_QNAME = new QName("", "not_decoded");
    private final static QName _ValidTimeFrom_QNAME = new QName("",
            "valid_time_from");
    private final static QName _MaxTempC_QNAME = new QName("", "max_temp_c");
    private final static QName _FcstTimeFrom_QNAME = new QName("",
            "fcst_time_from");
    private final static QName _WindShearDirDegrees_QNAME = new QName("",
            "wind_shear_dir_degrees");
    private final static QName _Warning_QNAME = new QName("", "warning");
    private final static QName _SfcTempC_QNAME = new QName("", "sfc_temp_c");
    private final static QName _Longitude_QNAME = new QName("", "longitude");
    private final static QName _RawText_QNAME = new QName("", "raw_text");
    private final static QName _ElevationM_QNAME = new QName("", "elevation_m");
    private final static QName _ValidTimeTo_QNAME = new QName("",
            "valid_time_to");
    private final static QName _WindDirDegrees_QNAME = new QName("",
            "wind_dir_degrees");
    private final static QName _ChangeIndicator_QNAME = new QName("",
            "change_indicator");
    private final static QName _Probability_QNAME = new QName("", "probability");
    private final static QName _RequestIndex_QNAME = new QName("",
            "request_index");
    private final static QName _StationId_QNAME = new QName("", "station_id");
    private final static QName _WindGustKt_QNAME = new QName("", "wind_gust_kt");
    private final static QName _WindSpeedKt_QNAME = new QName("",
            "wind_speed_kt");
    private final static QName _TimeBecoming_QNAME = new QName("",
            "time_becoming");
    private final static QName _VertVisFt_QNAME = new QName("", "vert_vis_ft");
    private final static QName _AltimInHg_QNAME = new QName("", "altim_in_hg");
    private final static QName _MinTempC_QNAME = new QName("", "min_temp_c");
    private final static QName _IssueTime_QNAME = new QName("", "issue_time");
    private final static QName _FcstTimeTo_QNAME = new QName("", "fcst_time_to");
    private final static QName _ValidTime_QNAME = new QName("", "valid_time");
    private final static QName _Remarks_QNAME = new QName("", "remarks");

    /**
     * Create a new ObjectFactory that can be used to create new instances of
     * schema derived classes for package: com.groundcontrol.taf
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Request }
     *
     */
    public Request createRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link Data }
     *
     */
    public Data createData() {
        return new Data();
    }

    /**
     * Create an instance of {@link TAF }
     *
     */
    public TAF createTAF() {
        return new TAF();
    }

    /**
     * Create an instance of {@link Forecast }
     *
     */
    public Forecast createForecast() {
        return new Forecast();
    }

    /**
     * Create an instance of {@link SkyCondition }
     *
     */
    public SkyCondition createSkyCondition() {
        return new SkyCondition();
    }

    /**
     * Create an instance of {@link TurbulenceCondition }
     *
     */
    public TurbulenceCondition createTurbulenceCondition() {
        return new TurbulenceCondition();
    }

    /**
     * Create an instance of {@link IcingCondition }
     *
     */
    public IcingCondition createIcingCondition() {
        return new IcingCondition();
    }

    /**
     * Create an instance of {@link Temperature }
     *
     */
    public Temperature createTemperature() {
        return new Temperature();
    }

    /**
     * Create an instance of {@link Warnings }
     *
     */
    public Warnings createWarnings() {
        return new Warnings();
    }

    /**
     * Create an instance of {@link DataSource }
     *
     */
    public DataSource createDataSource() {
        return new DataSource();
    }

    /**
     * Create an instance of {@link Response }
     *
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link Errors }
     *
     */
    public Errors createErrors() {
        return new Errors();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "wind_shear_hgt_ft_agl")
    public JAXBElement<Short> createWindShearHgtFtAgl(Short value) {
        return new JAXBElement<Short>(_WindShearHgtFtAgl_QNAME, Short.class,
                null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "visibility_statute_mi")
    public JAXBElement<Float> createVisibilityStatuteMi(Float value) {
        return new JAXBElement<Float>(_VisibilityStatuteMi_QNAME, Float.class,
                null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "latitude")
    public JAXBElement<Float> createLatitude(Float value) {
        return new JAXBElement<Float>(_Latitude_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "time_taken_ms")
    public JAXBElement<Integer> createTimeTakenMs(Integer value) {
        return new JAXBElement<Integer>(_TimeTakenMs_QNAME, Integer.class,
                null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "bulletin_time")
    public JAXBElement<String> createBulletinTime(String value) {
        return new JAXBElement<String>(_BulletinTime_QNAME, String.class, null,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "wind_shear_speed_kt")
    public JAXBElement<Integer> createWindShearSpeedKt(Integer value) {
        return new JAXBElement<Integer>(_WindShearSpeedKt_QNAME, Integer.class,
                null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "error")
    public JAXBElement<String> createError(String value) {
        return new JAXBElement<String>(_Error_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "wx_string")
    public JAXBElement<String> createWxString(String value) {
        return new JAXBElement<String>(_WxString_QNAME, String.class, null,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "not_decoded")
    public JAXBElement<String> createNotDecoded(String value) {
        return new JAXBElement<String>(_NotDecoded_QNAME, String.class, null,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "valid_time_from")
    public JAXBElement<String> createValidTimeFrom(String value) {
        return new JAXBElement<String>(_ValidTimeFrom_QNAME, String.class,
                null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "max_temp_c")
    public JAXBElement<String> createMaxTempC(String value) {
        return new JAXBElement<String>(_MaxTempC_QNAME, String.class, null,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "fcst_time_from")
    public JAXBElement<String> createFcstTimeFrom(String value) {
        return new JAXBElement<String>(_FcstTimeFrom_QNAME, String.class, null,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "wind_shear_dir_degrees")
    public JAXBElement<Short> createWindShearDirDegrees(Short value) {
        return new JAXBElement<Short>(_WindShearDirDegrees_QNAME, Short.class,
                null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "warning")
    public JAXBElement<String> createWarning(String value) {
        return new JAXBElement<String>(_Warning_QNAME, String.class, null,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "sfc_temp_c")
    public JAXBElement<Float> createSfcTempC(Float value) {
        return new JAXBElement<Float>(_SfcTempC_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "longitude")
    public JAXBElement<Float> createLongitude(Float value) {
        return new JAXBElement<Float>(_Longitude_QNAME, Float.class, null,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "raw_text")
    public JAXBElement<String> createRawText(String value) {
        return new JAXBElement<String>(_RawText_QNAME, String.class, null,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "elevation_m")
    public JAXBElement<Float> createElevationM(Float value) {
        return new JAXBElement<Float>(_ElevationM_QNAME, Float.class, null,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "valid_time_to")
    public JAXBElement<String> createValidTimeTo(String value) {
        return new JAXBElement<String>(_ValidTimeTo_QNAME, String.class, null,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "wind_dir_degrees")
    public JAXBElement<Short> createWindDirDegrees(Short value) {
        return new JAXBElement<Short>(_WindDirDegrees_QNAME, Short.class, null,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "change_indicator")
    public JAXBElement<String> createChangeIndicator(String value) {
        return new JAXBElement<String>(_ChangeIndicator_QNAME, String.class,
                null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "probability")
    public JAXBElement<Integer> createProbability(Integer value) {
        return new JAXBElement<Integer>(_Probability_QNAME, Integer.class,
                null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "request_index")
    public JAXBElement<Integer> createRequestIndex(Integer value) {
        return new JAXBElement<Integer>(_RequestIndex_QNAME, Integer.class,
                null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "station_id")
    public JAXBElement<String> createStationId(String value) {
        return new JAXBElement<String>(_StationId_QNAME, String.class, null,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "wind_gust_kt")
    public JAXBElement<Integer> createWindGustKt(Integer value) {
        return new JAXBElement<Integer>(_WindGustKt_QNAME, Integer.class, null,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "wind_speed_kt")
    public JAXBElement<Integer> createWindSpeedKt(Integer value) {
        return new JAXBElement<Integer>(_WindSpeedKt_QNAME, Integer.class,
                null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "time_becoming")
    public JAXBElement<String> createTimeBecoming(String value) {
        return new JAXBElement<String>(_TimeBecoming_QNAME, String.class, null,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "vert_vis_ft")
    public JAXBElement<Short> createVertVisFt(Short value) {
        return new JAXBElement<Short>(_VertVisFt_QNAME, Short.class, null,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "altim_in_hg")
    public JAXBElement<Float> createAltimInHg(Float value) {
        return new JAXBElement<Float>(_AltimInHg_QNAME, Float.class, null,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "min_temp_c")
    public JAXBElement<String> createMinTempC(String value) {
        return new JAXBElement<String>(_MinTempC_QNAME, String.class, null,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "issue_time")
    public JAXBElement<String> createIssueTime(String value) {
        return new JAXBElement<String>(_IssueTime_QNAME, String.class, null,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "fcst_time_to")
    public JAXBElement<String> createFcstTimeTo(String value) {
        return new JAXBElement<String>(_FcstTimeTo_QNAME, String.class, null,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "valid_time")
    public JAXBElement<String> createValidTime(String value) {
        return new JAXBElement<String>(_ValidTime_QNAME, String.class, null,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     *
     */
    @XmlElementDecl(namespace = "", name = "remarks")
    public JAXBElement<String> createRemarks(String value) {
        return new JAXBElement<String>(_Remarks_QNAME, String.class, null,
                value);
    }

}
