/**
 * MIT License
 * <p>
 * Copyright (c) 2017 grndctl
 * <p>
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * <p>
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * <p>
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.06 at 02:18:46 PM EST 
//

package com.grndctl.model.taf;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}raw_text" minOccurs="0"/>
 *         &lt;element ref="{}station_id" minOccurs="0"/>
 *         &lt;element ref="{}issue_time" minOccurs="0"/>
 *         &lt;element ref="{}bulletin_time" minOccurs="0"/>
 *         &lt;element ref="{}valid_time_from" minOccurs="0"/>
 *         &lt;element ref="{}valid_time_to" minOccurs="0"/>
 *         &lt;element ref="{}remarks" minOccurs="0"/>
 *         &lt;element ref="{}latitude" minOccurs="0"/>
 *         &lt;element ref="{}longitude" minOccurs="0"/>
 *         &lt;element ref="{}elevation_m" minOccurs="0"/>
 *         &lt;element ref="{}forecast" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"rawText", "stationId", "issueTime",
        "bulletinTime", "validTimeFrom", "validTimeTo", "remarks", "latitude",
        "longitude", "elevationM", "forecast"})
@XmlRootElement(name = "TAF")
public class TAF {

    @XmlElement(name = "raw_text")
    protected String rawText;
    @XmlElement(name = "station_id")
    protected String stationId;
    @XmlElement(name = "issue_time")
    protected String issueTime;
    @XmlElement(name = "bulletin_time")
    protected String bulletinTime;
    @XmlElement(name = "valid_time_from")
    protected String validTimeFrom;
    @XmlElement(name = "valid_time_to")
    protected String validTimeTo;
    protected String remarks;
    protected Float latitude;
    protected Float longitude;
    @XmlElement(name = "elevation_m")
    protected Float elevationM;
    protected List<Forecast> forecast;

    /**
     * Gets the value of the rawText property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getRawText() {
        return rawText;
    }

    /**
     * Sets the value of the rawText property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setRawText(String value) {
        this.rawText = value;
    }

    /**
     * Gets the value of the stationId property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getStationId() {
        return stationId;
    }

    /**
     * Sets the value of the stationId property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setStationId(String value) {
        this.stationId = value;
    }

    /**
     * Gets the value of the issueTime property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getIssueTime() {
        return issueTime;
    }

    /**
     * Sets the value of the issueTime property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setIssueTime(String value) {
        this.issueTime = value;
    }

    /**
     * Gets the value of the bulletinTime property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getBulletinTime() {
        return bulletinTime;
    }

    /**
     * Sets the value of the bulletinTime property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setBulletinTime(String value) {
        this.bulletinTime = value;
    }

    /**
     * Gets the value of the validTimeFrom property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getValidTimeFrom() {
        return validTimeFrom;
    }

    /**
     * Sets the value of the validTimeFrom property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setValidTimeFrom(String value) {
        this.validTimeFrom = value;
    }

    /**
     * Gets the value of the validTimeTo property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getValidTimeTo() {
        return validTimeTo;
    }

    /**
     * Sets the value of the validTimeTo property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setValidTimeTo(String value) {
        this.validTimeTo = value;
    }

    /**
     * Gets the value of the remarks property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * Sets the value of the remarks property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setRemarks(String value) {
        this.remarks = value;
    }

    /**
     * Gets the value of the latitude property.
     *
     * @return possible object is {@link Float }
     *
     */
    public Float getLatitude() {
        return latitude;
    }

    /**
     * Sets the value of the latitude property.
     *
     * @param value
     *            allowed object is {@link Float }
     *
     */
    public void setLatitude(Float value) {
        this.latitude = value;
    }

    /**
     * Gets the value of the longitude property.
     *
     * @return possible object is {@link Float }
     *
     */
    public Float getLongitude() {
        return longitude;
    }

    /**
     * Sets the value of the longitude property.
     *
     * @param value
     *            allowed object is {@link Float }
     *
     */
    public void setLongitude(Float value) {
        this.longitude = value;
    }

    /**
     * Gets the value of the elevationM property.
     *
     * @return possible object is {@link Float }
     *
     */
    public Float getElevationM() {
        return elevationM;
    }

    /**
     * Sets the value of the elevationM property.
     *
     * @param value
     *            allowed object is {@link Float }
     *
     */
    public void setElevationM(Float value) {
        this.elevationM = value;
    }

    /**
     * Gets the value of the forecast property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the forecast property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getForecast().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Forecast }
     *
     *
     */
    public List<Forecast> getForecast() {
        if (forecast == null) {
            forecast = new ArrayList<Forecast>();
        }
        return this.forecast;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        TAF taf = (TAF) o;

        if (bulletinTime != null ? !bulletinTime.equals(taf.bulletinTime) : taf.bulletinTime != null) return false;
        if (elevationM != null ? !elevationM.equals(taf.elevationM) : taf.elevationM != null) return false;
        if (issueTime != null ? !issueTime.equals(taf.issueTime) : taf.issueTime != null) return false;
        if (latitude != null ? !latitude.equals(taf.latitude) : taf.latitude != null) return false;
        if (longitude != null ? !longitude.equals(taf.longitude) : taf.longitude != null) return false;
        if (rawText != null ? !rawText.equals(taf.rawText) : taf.rawText != null) return false;
        if (remarks != null ? !remarks.equals(taf.remarks) : taf.remarks != null) return false;
        if (stationId != null ? !stationId.equals(taf.stationId) : taf.stationId != null) return false;
        if (validTimeFrom != null ? !validTimeFrom.equals(taf.validTimeFrom) : taf.validTimeFrom != null) return false;
        if (validTimeTo != null ? !validTimeTo.equals(taf.validTimeTo) : taf.validTimeTo != null) return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = rawText != null ? rawText.hashCode() : 0;
        result = 31 * result + (stationId != null ? stationId.hashCode() : 0);
        result = 31 * result + (issueTime != null ? issueTime.hashCode() : 0);
        result = 31 * result + (bulletinTime != null ? bulletinTime.hashCode() : 0);
        result = 31 * result + (validTimeFrom != null ? validTimeFrom.hashCode() : 0);
        result = 31 * result + (validTimeTo != null ? validTimeTo.hashCode() : 0);
        result = 31 * result + (remarks != null ? remarks.hashCode() : 0);
        result = 31 * result + (latitude != null ? latitude.hashCode() : 0);
        result = 31 * result + (longitude != null ? longitude.hashCode() : 0);
        result = 31 * result + (elevationM != null ? elevationM.hashCode() : 0);
        return result;
    }
}
