/**
 * MIT License
 * <p>
 * Copyright (c) 2018 grndctl-akka
 * <p>
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * <p>
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * <p>
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.06 at 02:18:46 PM EST 
//

package com.grndctl.model.taf;

import javax.xml.bind.annotation.*;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}valid_time"/>
 *         &lt;element ref="{}sfc_temp_c" minOccurs="0"/>
 *         &lt;element ref="{}max_temp_c" minOccurs="0"/>
 *         &lt;element ref="{}min_temp_c" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"validTime", "sfcTempC", "maxTempC",
        "minTempC"})
@XmlRootElement(name = "temperature")
public class Temperature {

    @XmlElement(name = "valid_time", required = true)
    protected String validTime;
    @XmlElement(name = "sfc_temp_c")
    protected Float sfcTempC;
    @XmlElement(name = "max_temp_c")
    protected String maxTempC;
    @XmlElement(name = "min_temp_c")
    protected String minTempC;

    /**
     * Gets the fromString of the validTime property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getValidTime() {
        return validTime;
    }

    /**
     * Sets the fromString of the validTime property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setValidTime(String value) {
        this.validTime = value;
    }

    /**
     * Gets the fromString of the sfcTempC property.
     *
     * @return possible object is {@link Float }
     *
     */
    public Float getSfcTempC() {
        return sfcTempC;
    }

    /**
     * Sets the fromString of the sfcTempC property.
     *
     * @param value
     *            allowed object is {@link Float }
     *
     */
    public void setSfcTempC(Float value) {
        this.sfcTempC = value;
    }

    /**
     * Gets the fromString of the maxTempC property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getMaxTempC() {
        return maxTempC;
    }

    /**
     * Sets the fromString of the maxTempC property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setMaxTempC(String value) {
        this.maxTempC = value;
    }

    /**
     * Gets the fromString of the minTempC property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getMinTempC() {
        return minTempC;
    }

    /**
     * Sets the fromString of the minTempC property.
     *
     * @param value
     *            allowed object is {@link String }
     *
     */
    public void setMinTempC(String value) {
        this.minTempC = value;
    }

}
